package com.bsoft.ov8.loader.services;// Or wherever you want to place this utility

import lombok.extern.slf4j.Slf4j;
import nl.overheid.omgevingswet.ozon.geodownload.model.GeoJsonGeometry;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.PrecisionModel;
import org.locationtech.jts.io.


// Assuming GeoJsonGeometry is a class generated by OpenAPI,
// and you can get a GeoJSON string from it.
// If your OpenAPI generated GeoJsonGeometry is just a String,
// then you can directly pass that string.
// import nl.overheid.omgevingswet.ozon.geodownload.model.GeoJsonGeometry; // Example import if it's a POJO
@Slf4j
public class GeometryConverter {


    private final GeoJsonReader geoJsonReader;
    private final GeometryFactory geometryFactory;

    // You might want to inject this as a Spring bean if used frequently
    public GeometryConverter() {
        // SRID 28992 for RD_New (Rijksdriehoekmeting)
        // PrecisionModel.FLOATING is standard for most operations
        this.geometryFactory = new GeometryFactory(new PrecisionModel(), 28992);
        this.geoJsonReader = new GeoJsonReader(this.geometryFactory);
    }

    /**
     * Converts a GeoJSON string to a JTS Geometry object.
     *
     * @param geoJsonString The GeoJSON representation of the geometry.
     * @return The JTS Geometry object, or null if conversion fails.
     */
    public Geometry convertGeoJsonToJtsGeometry(String geoJsonString) {
        if (geoJsonString == null || geoJsonString.trim().isEmpty()) {
            log.warn("Attempted to convert null or empty GeoJSON string to JTS Geometry.");
            return null;
        }
        try {
            return geoJsonReader.read(geoJsonString);
        } catch (Exception e) { // Catching generic Exception for robustness in case of parsing errors
            log.error("Failed to convert GeoJSON string to JTS Geometry: {}", geoJsonString, e);
            return null;
        }
    }

    // If your OpenAPI generator creates a POJO for GeoJsonGeometry,
    // you might need a method to extract the raw JSON string from it first.
    // This depends on how 'nl.overheid.omgevingswet.ozon.geodownload.model.GeoJsonGeometry' is structured.
    // Example (hypothetical, adjust based on actual GeoJsonGeometry structure):

    public Geometry convertGeoJsonPojoToJtsGeometry(GeoJsonGeometry geoJsonPojo) {
        if (geoJsonPojo == null) {
            return null;
        }
        // Assuming your GeoJsonGeometry POJO has a way to get the raw JSON string,
        // or can be directly serialized to JSON.
        // For example, if it has a 'toGeoJsonString()' method or if it's just a wrapper around a String.
        String geoJsonString = geoJsonPojo.toString(); // Hypothetical method
        return convertGeoJsonToJtsGeometry(geoJsonString);
    }

}