logging:
  level:
    org:
      apache:
        http: DEBUG
      springframework:
        security: INFO
        web:
          reactive:
            function:
              client: DEBUG
          client: DEBUG
    com:
      bsoft: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
          HttpClient: DEBUG
  # --- Logging to File Configuration ---
  file:
    name: logs/application.log # Specifies the full path and name of the log file.
    # 'logs/' indicates a 'logs' directory relative to your application's JAR.

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{30} - %msg%n" # Custom pattern for file output
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{30} - %msg%n" # Keep your console pattern if desired
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ov8}
    username: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ov8}
    user: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    validateMigrationNaming: true
    locations: classpath:db/migration
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
info:
  project:
    name: ${spring.application.name}
    version: @project.version@
    description: @project.description@
  environment: ${spring.profiles.active}

management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
    metrics:
      access: read_only
    prometheus:
      access: read_only
    shutdown:
      access: unrestricted
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      path-mapping:
        info: app-info
        health: app-health
      exposure:
        include: '*'
        exclude:
  server:
    port: 8080

api:
  ozon:
    base-url: ${OZON_BASE_URL:https://service.omgevingswet.overheid.nl/publiek/omgevingsdocumenten/api/presenteren/v8}
    api-key: ${OZON_API_KEY:8b9b4c2f-81a8-490a-acf4-82d82c77beee} # Replace with your actual API key
