create table ontwerpregeling
(
    id                          bigint                   not null primary key,
    identificatie               text                     not null,
    officieletitel              text                     not null,
    ontwerpbesluitidentificatie text                     not null,
    besluitciteertitel          text,
    technischid                 text                     not null,
    expressionid                text,
    versie                      NUMERIC                  not null,
    tijdstipregistratie         TIMESTAMP WITH TIME ZONE not null,
    eindregistratie             TIMESTAMP WITH TIME ZONE,
    opschrift                   text,
    citeertitel                 text,
    conditie                    text,
    heeftbijlagen               boolean,
    heefttoelichtingen          boolean,
    isvervangregeling           boolean,
    publicatieID                text,
    bekendop                    text,
    ontvangenop                 text,
    bevoegdgezag_id             bigint                   not null,
    soortregeling_id            bigint                   not null
);

create index ontwerpregeling_identificatie_ix on ontwerpregeling (identificatie);
create index ontwerpregeling_bevoegdgezag_ix on ontwerpregeling (bevoegdgezag_id);
create index ontwerpregeling_soortregeling_ix on ontwerpregeling (soortregeling_id);
create index ontwerpregeling_identificatie_versie on ontwerpregeling (identificatie, versie);
create index ontwerpregeling_tijdstipregistratie_eindregistratie on ontwerpregeling (tijdstipregistratie, eindregistratie);

ALTER TABLE ontwerpregeling
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME ontwerpregeling_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);