create table bevoegdgezag
(
    id           bigint not null primary key,
    naam         text   not null,
    bestuurslaag text   not null,
    code         text   not null
);

create unique index bevoegdgezag_code on bevoegdgezag (code);

ALTER TABLE bevoegdgezag
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME bevoegdgezag_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);