create table soortstap
(
    id     bigint not null primary key,
    code   text,
    waarde text
);

create unique index soortstap_code_ix on soortstap (code);

ALTER TABLE soortstap
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME soortstap_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);