create table regeling_opvolgervan
(
    id                  bigint not null primary key,
    regeling_id         bigint,
    opvolgerregeling_id bigint
);

create unique index regeling_opvolgervan_regeling_opvolgerregeling on regeling_opvolgervan (regeling_id, opvolgerregeling_id);

ALTER TABLE regeling_opvolgervan
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME regeling_opvolgervan_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);