create table regeling_soortregeling
(
    id               bigint not null primary key,
    regeling_id      bigint,
    soortregeling_id bigint
);

create unique index regeling_soortregeling_ix on regeling_soortregeling (regeling_id, soortregeling_id);

ALTER TABLE regeling_soortregeling
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME regeling_soortregeling_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);