create table locatie
(
    id                     bigint                   not null primary key,
    identificatie          text,
    geometrieidentificatie text,
    locatietype            text,
    noemer                 text,
    ispons                 boolean,
    minx                   bigint,
    miny                   bigint,
    maxx                   bigint,
    maxy                   bigint,
    versie                 NUMERIC,
    begininwerking         DATE                     not null,
    begingeldigheid        DATE                     not null,
    eindgeldigheid         DATE,
    tijdstipregistratie    TIMESTAMP WITH TIME ZONE not null,
    eindregistratie        TIMESTAMP WITH TIME ZONE,
    parent_group_id        bigint
);

create unique index locatie_geometrieidentificatie on locatie (identificatie, geometrieidentificatie);
create unique index locatie_parent_group on locatie (parent_group_id, id);

ALTER TABLE locatie
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME locatie_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);