create table soortregeling
(
    id     bigint not null primary key,
    code   text   not null,
    waarde text   not null
);

create unique index soortregeling_code on soortregeling (code);

ALTER TABLE soortregeling
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME soortregeling_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);