create table regeling
(
    id                  bigint                   not null primary key,
    identificatie       text                     not null,
    officieleTitel      text                     not null,
    versie              NUMERIC,
    beginInwerking      DATE                     not null,
    beginGeldigheid     DATE                     not null,
    eindGeldigheid      DATE,
    tijdstipRegistratie TIMESTAMP WITH TIME ZONE not null,
    eindRegistratie     TIMESTAMP WITH TIME ZONE,
    citeerTitel         text,
    opschrift           text,
    conditie            text,
    heeftBijlagen       boolean,
    heeftToelichtingen  boolean,
    publicatieID        text,
    inwerkingTot        text,
    geldigTot           text
);

create index regeling_identificatie_ix on regeling (identificatie);
create unique index regeling_identificatie_versie on regeling (identificatie, versie);
create index regeling_beginGeldigheid_eindgeldigheid on regeling (beginGeldigheid, eindGeldigheid);

ALTER TABLE regeling
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME regeling_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);