create table regeling_bevoegdgezag
(
    id              bigint not null primary key,
    regeling_id     bigint,
    bevoegdgezag_id bigint
);

create unique index regeling_bevoegdgezag_ix on regeling_bevoegdgezag (regeling_id, bevoegdgezag_id);

ALTER TABLE regeling_bevoegdgezag
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME regeling_bevoegdgezag_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);