create table regeling_regelingsgebied
(
    id          bigint not null primary key,
    regeling_id bigint,
    locatie_id  bigint
);

create unique index regeling_regelingsgebied_regeling_locatie on regeling_regelingsgebied (regeling_id, locatie_id);

ALTER TABLE regeling_regelingsgebied
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME regeling_regelingsgebied_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);