create table procedurestap
(
    id           bigint not null primary key,
    soortstap_id bigint,
    actor        text,
    voltooidop   text
);

create index procedurestap_voltooidop_ix on procedurestap (voltooidop);

ALTER TABLE procedurestap
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME procedurestap_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);