create table procedureverloop
(
    id     bigint not null primary key,
    bekendOp   text,
    ontvangenOp text,
    ontwerpregeling_id bigint
);

create unique index procedureverloop_ontwerpregeling_ix on procedureverloop (ontwerpregeling_id);

ALTER TABLE procedureverloop
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME procedureverloop_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);