create table soortstapxx
(
    id     bigint not null primary key,
    bekendOp   text,
    ontvangenOp text,
    procedureverloop_id bigint
);

create unique index soortstapxx_procedureverloop_ix on soortstapxx (procedureverloop_id);

ALTER TABLE soortstapxx
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME soortstapxx_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);