create table ontwerpregeling_regelingsgebied
(
    id                 bigint not null primary key,
    ontwerpregeling_id bigint,
    ontwerplocatie_id  bigint
);

create unique index ontwerpregeling_regelingsgebied_ontwerpregeling_locatie on ontwerpregeling_regelingsgebied (ontwerpregeling_id, ontwerplocatie_id);

ALTER TABLE ontwerpregeling_regelingsgebied
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME ontwerpregeling_regelingsgebied_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);