CREATE
EXTENSION IF NOT EXISTS postgis;

create table geo
(
    id        bigint not null primary key,
    geoid     text   not null,
    geometrie geometry(Geometry, 28992) not null
);

create unique index geo_geoid_ix on geo (geoid);

create index geo_geometrie_idx
    on geo using gist (geometrie);

ALTER TABLE geo
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME geo_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);