
create table ontwerplocatie
(
    id                     bigint                   not null primary key,
    identificatie          text,
    ontwerpbesluitid text,
    technischid text,
    geometrieidentificatie text,
    locatietype            text,
    noemer                 text,
    status text,
    minx                   bigint,
    miny                   bigint,
    maxx                   bigint,
    maxy                   bigint,
    versie                 NUMERIC,
    begininwerking         DATE                     not null,
    begingeldigheid        DATE                     not null,
    eindgeldigheid         DATE,
    tijdstipregistratie    TIMESTAMP WITH TIME ZONE not null,
    eindregistratie        TIMESTAMP WITH TIME ZONE,
    parent_group_id        bigint
);

create unique index ontwerplocatie_geometrieidentificatie on ontwerplocatie (identificatie, geometrieidentificatie);
create unique index ontwerplocatie_parent_group on ontwerplocatie (parent_group_id, id);

ALTER TABLE ontwerplocatie
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME ontwerplocatie_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);